spring:
  # Datasource配置
  datasource:
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: 675844

  # Thymeleaf配置
  thymeleaf:
    encoding: UTF-8

  # Redis配置
  redis:
    database: 0
    host: 47.107.227.25
    port: 6379
    password: 675844
    timeout: 5000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0

# MyBatis配置
mybatis:
  # Mapper映射文件的位置
  mapper-locations: classpath:mapper/*.xml
  # 包下所有类的别名，配置别名为了在对象映射文件中接收参数类型和返回参数类型时省略包路径
  type-aliases-package: com.daniel.seckill.model