spring:
  # Datasource配置
  datasource:
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&useSSL=false&useAffectedRows=true&characterEncoding=utf8
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver

    # Druid连接池配置
    druid:
      max-active: 1000
      filters: stat
      initial-size: 100
      max-wait: 60000
      min-idle: 500
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20

  # Static配置
  resources:
    add-mappings: true
    chain:
      cache: true
      enabled: true
      gzipped: true
      html-application-cache: true
    static-locations: classpath:/static/

  # Thymeleaf配置
  thymeleaf:
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    enabled: true
    mode: HTML5

  # Redis配置
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 100000
    jedis:
      pool:
        max-total: 1000
        max-wait: 500
        max-idle: 500
        min-idle: 0

# MyBatis配置
mybatis:
  # Mapper映射文件的位置
  mapper-locations: classpath:mapper/*.xml
  # 包下所有类的别名，配置别名为了在对象映射文件中接收参数类型和返回参数类型时省略包路径
  type-aliases-package: com.daniel.seckill.model